# coding: utf-8

"""
    ngsi-v2

    NGSI V2 API RC-2018.04  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.registrations_api import RegistrationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRegistrationsApi(unittest.TestCase):
    """RegistrationsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.registrations_api.RegistrationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_registrations(self):
        """Test case for create_registrations

        """
        pass

    def test_delete_registration(self):
        """Test case for delete_registration

        """
        pass

    def test_retrieve_registration(self):
        """Test case for retrieve_registration

        """
        pass

    def test_retrieve_registrations(self):
        """Test case for retrieve_registrations

        """
        pass

    def test_update_registration(self):
        """Test case for update_registration

        """
        pass


if __name__ == '__main__':
    unittest.main()
