# coding: utf-8

"""
    ngsi-v2

    NGSI V2 API RC-2018.04  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.data_provided_expression import DataProvidedExpression  # noqa: E501
from swagger_client.rest import ApiException


class TestDataProvidedExpression(unittest.TestCase):
    """DataProvidedExpression unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataProvidedExpression(self):
        """Test DataProvidedExpression"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.data_provided_expression.DataProvidedExpression()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
