# coding: utf-8

"""
    ngsi-v2

    NGSI V2 API RC-2018.04  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.subscriptions_api import SubscriptionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.subscriptions_api.SubscriptionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_a_new_subscription(self):
        """Test case for create_a_new_subscription

        """
        pass

    def test_delete_subscription(self):
        """Test case for delete_subscription

        """
        pass

    def test_retrieve_subscription(self):
        """Test case for retrieve_subscription

        """
        pass

    def test_retrieve_subscriptions(self):
        """Test case for retrieve_subscriptions

        """
        pass

    def test_update_subscription(self):
        """Test case for update_subscription

        """
        pass


if __name__ == '__main__':
    unittest.main()
