# coding: utf-8

"""
    ngsi-v2

    NGSI V2 API RC-2018.04  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.batch_operations_api import BatchOperationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBatchOperationsApi(unittest.TestCase):
    """BatchOperationsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.batch_operations_api.BatchOperationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_notify(self):
        """Test case for notify

        """
        pass

    def test_query(self):
        """Test case for query

        """
        pass

    def test_update(self):
        """Test case for update

        """
        pass


if __name__ == '__main__':
    unittest.main()
