# coding: utf-8

"""
    ngsi-v2

    NGSI V2 API RC-2018.04  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.attributes_api import AttributesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAttributesApi(unittest.TestCase):
    """AttributesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.attributes_api.AttributesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_attribute_data(self):
        """Test case for get_attribute_data

        """
        pass

    def test_remove_a_single_attribute(self):
        """Test case for remove_a_single_attribute

        """
        pass

    def test_update_attribute_data(self):
        """Test case for update_attribute_data

        """
        pass


if __name__ == '__main__':
    unittest.main()
