# coding: utf-8

"""
    ngsi-v2-2016.10

    NGSI V2 API  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.attribute_value_api import AttributeValueApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAttributeValueApi(unittest.TestCase):
    """AttributeValueApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.attribute_value_api.AttributeValueApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_attribute_value(self):
        """Test case for get_attribute_value

        """
        pass

    def test_update_attribute_value(self):
        """Test case for update_attribute_value

        """
        pass


if __name__ == '__main__':
    unittest.main()
