# coding: utf-8

"""
    ngsi-v2-2016.10

    NGSI V2 API  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.api_entry_point_api import APIEntryPointApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAPIEntryPointApi(unittest.TestCase):
    """APIEntryPointApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.api_entry_point_api.APIEntryPointApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrieve_api_resources(self):
        """Test case for retrieve_api_resources

        """
        pass


if __name__ == '__main__':
    unittest.main()
