# coding: utf-8

# flake8: noqa

"""
    ngsi-v2

    NGSI V2 API  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.api_entry_point_api import APIEntryPointApi
from swagger_client.api.attribute_value_api import AttributeValueApi
from swagger_client.api.attributes_api import AttributesApi
from swagger_client.api.batch_operations_api import BatchOperationsApi
from swagger_client.api.entities_api import EntitiesApi
from swagger_client.api.subscriptions_api import SubscriptionsApi
from swagger_client.api.types_api import TypesApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.api_entry_point import APIEntryPoint
from swagger_client.models.attribute import Attribute
from swagger_client.models.attribute_value import AttributeValue
from swagger_client.models.batch_operation import BatchOperation
from swagger_client.models.entity import Entity
from swagger_client.models.entity_type import EntityType
from swagger_client.models.error_response import ErrorResponse
from swagger_client.models.query import Query
from swagger_client.models.query_pattern import QueryPattern
from swagger_client.models.subscription import Subscription
