# coding: utf-8

# flake8: noqa
"""
    ngsi-v2-2016.10

    NGSI V2 API  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.attribute import Attribute
from swagger_client.models.attribute_value import AttributeValue
from swagger_client.models.batch_operation import BatchOperation
from swagger_client.models.entity import Entity
from swagger_client.models.entity_type import EntityType
from swagger_client.models.error_response import ErrorResponse
from swagger_client.models.query import Query
from swagger_client.models.query_pattern import QueryPattern
from swagger_client.models.subscription import Subscription
