# coding: utf-8

"""
    ngsi-v2

    NGSI V2 API RC-2018.04  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RegistrationResponseForwardingInformation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'time_sent': 'int',
        'last_forwarding': 'datetime',
        'last_failure': 'datetime',
        'last_success': 'datetime'
    }

    attribute_map = {
        'time_sent': 'timeSent',
        'last_forwarding': 'lastForwarding',
        'last_failure': 'lastFailure',
        'last_success': 'lastSuccess'
    }

    def __init__(self, time_sent=None, last_forwarding=None, last_failure=None, last_success=None):  # noqa: E501
        """RegistrationResponseForwardingInformation - a model defined in Swagger"""  # noqa: E501

        self._time_sent = None
        self._last_forwarding = None
        self._last_failure = None
        self._last_success = None
        self.discriminator = None

        if time_sent is not None:
            self.time_sent = time_sent
        if last_forwarding is not None:
            self.last_forwarding = last_forwarding
        if last_failure is not None:
            self.last_failure = last_failure
        if last_success is not None:
            self.last_success = last_success

    @property
    def time_sent(self):
        """Gets the time_sent of this RegistrationResponseForwardingInformation.  # noqa: E501


        :return: The time_sent of this RegistrationResponseForwardingInformation.  # noqa: E501
        :rtype: int
        """
        return self._time_sent

    @time_sent.setter
    def time_sent(self, time_sent):
        """Sets the time_sent of this RegistrationResponseForwardingInformation.


        :param time_sent: The time_sent of this RegistrationResponseForwardingInformation.  # noqa: E501
        :type: int
        """

        self._time_sent = time_sent

    @property
    def last_forwarding(self):
        """Gets the last_forwarding of this RegistrationResponseForwardingInformation.  # noqa: E501


        :return: The last_forwarding of this RegistrationResponseForwardingInformation.  # noqa: E501
        :rtype: datetime
        """
        return self._last_forwarding

    @last_forwarding.setter
    def last_forwarding(self, last_forwarding):
        """Sets the last_forwarding of this RegistrationResponseForwardingInformation.


        :param last_forwarding: The last_forwarding of this RegistrationResponseForwardingInformation.  # noqa: E501
        :type: datetime
        """

        self._last_forwarding = last_forwarding

    @property
    def last_failure(self):
        """Gets the last_failure of this RegistrationResponseForwardingInformation.  # noqa: E501


        :return: The last_failure of this RegistrationResponseForwardingInformation.  # noqa: E501
        :rtype: datetime
        """
        return self._last_failure

    @last_failure.setter
    def last_failure(self, last_failure):
        """Sets the last_failure of this RegistrationResponseForwardingInformation.


        :param last_failure: The last_failure of this RegistrationResponseForwardingInformation.  # noqa: E501
        :type: datetime
        """

        self._last_failure = last_failure

    @property
    def last_success(self):
        """Gets the last_success of this RegistrationResponseForwardingInformation.  # noqa: E501


        :return: The last_success of this RegistrationResponseForwardingInformation.  # noqa: E501
        :rtype: datetime
        """
        return self._last_success

    @last_success.setter
    def last_success(self, last_success):
        """Sets the last_success of this RegistrationResponseForwardingInformation.


        :param last_success: The last_success of this RegistrationResponseForwardingInformation.  # noqa: E501
        :type: datetime
        """

        self._last_success = last_success

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RegistrationResponseForwardingInformation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
