# coding: utf-8

"""
    ngsi-v2

    NGSI V2 API RC-2018.04  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.query_pattern import QueryPattern  # noqa: F401,E501
from swagger_client.models.subscription_subject_conditions import SubscriptionSubjectConditions  # noqa: F401,E501


class SubscriptionSubject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entities': 'list[QueryPattern]',
        'conditions': 'SubscriptionSubjectConditions'
    }

    attribute_map = {
        'entities': 'entities',
        'conditions': 'conditions'
    }

    def __init__(self, entities=None, conditions=None):  # noqa: E501
        """SubscriptionSubject - a model defined in Swagger"""  # noqa: E501

        self._entities = None
        self._conditions = None
        self.discriminator = None

        if entities is not None:
            self.entities = entities
        if conditions is not None:
            self.conditions = conditions

    @property
    def entities(self):
        """Gets the entities of this SubscriptionSubject.  # noqa: E501


        :return: The entities of this SubscriptionSubject.  # noqa: E501
        :rtype: list[QueryPattern]
        """
        return self._entities

    @entities.setter
    def entities(self, entities):
        """Sets the entities of this SubscriptionSubject.


        :param entities: The entities of this SubscriptionSubject.  # noqa: E501
        :type: list[QueryPattern]
        """

        self._entities = entities

    @property
    def conditions(self):
        """Gets the conditions of this SubscriptionSubject.  # noqa: E501


        :return: The conditions of this SubscriptionSubject.  # noqa: E501
        :rtype: SubscriptionSubjectConditions
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """Sets the conditions of this SubscriptionSubject.


        :param conditions: The conditions of this SubscriptionSubject.  # noqa: E501
        :type: SubscriptionSubjectConditions
        """

        self._conditions = conditions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubscriptionSubject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
