# coding: utf-8

"""
    ngsi-v2

    NGSI V2 API RC-2018.04  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.opquery_expression import OpqueryExpression  # noqa: F401,E501


class SubscriptionSubjectConditions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'attrs': 'list[str]',
        'expression': 'OpqueryExpression'
    }

    attribute_map = {
        'attrs': 'attrs',
        'expression': 'expression'
    }

    def __init__(self, attrs=None, expression=None):  # noqa: E501
        """SubscriptionSubjectConditions - a model defined in Swagger"""  # noqa: E501

        self._attrs = None
        self._expression = None
        self.discriminator = None

        if attrs is not None:
            self.attrs = attrs
        if expression is not None:
            self.expression = expression

    @property
    def attrs(self):
        """Gets the attrs of this SubscriptionSubjectConditions.  # noqa: E501


        :return: The attrs of this SubscriptionSubjectConditions.  # noqa: E501
        :rtype: list[str]
        """
        return self._attrs

    @attrs.setter
    def attrs(self, attrs):
        """Sets the attrs of this SubscriptionSubjectConditions.


        :param attrs: The attrs of this SubscriptionSubjectConditions.  # noqa: E501
        :type: list[str]
        """

        self._attrs = attrs

    @property
    def expression(self):
        """Gets the expression of this SubscriptionSubjectConditions.  # noqa: E501


        :return: The expression of this SubscriptionSubjectConditions.  # noqa: E501
        :rtype: OpqueryExpression
        """
        return self._expression

    @expression.setter
    def expression(self, expression):
        """Sets the expression of this SubscriptionSubjectConditions.


        :param expression: The expression of this SubscriptionSubjectConditions.  # noqa: E501
        :type: OpqueryExpression
        """

        self._expression = expression

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubscriptionSubjectConditions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
