# coding: utf-8

"""
    ngsi-v2

    NGSI V2 API RC-2018.04  # noqa: E501

    OpenAPI spec version: v2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class EntitiesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_entity(self, body, **kwargs):  # noqa: E501
        """create_entity  # noqa: E501

        The payload is an object representing the entity to be created. The object follows the JSON entity Representation format (described in a \"JSON Entity Representation\" section). Response: * Successful operation uses 201 Created or 204 No Content (if upsert option is used). Response includes a `Location` header with the URL of the   created entity. * Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for   more details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.create_entity(body, async=True)
        >>> result = thread.get()

        :param async bool
        :param Entity body: JSON Entity Representation (required)
        :param str options: Options dictionary
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.create_entity_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.create_entity_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def create_entity_with_http_info(self, body, **kwargs):  # noqa: E501
        """create_entity  # noqa: E501

        The payload is an object representing the entity to be created. The object follows the JSON entity Representation format (described in a \"JSON Entity Representation\" section). Response: * Successful operation uses 201 Created or 204 No Content (if upsert option is used). Response includes a `Location` header with the URL of the   created entity. * Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for   more details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.create_entity_with_http_info(body, async=True)
        >>> result = thread.get()

        :param async bool
        :param Entity body: JSON Entity Representation (required)
        :param str options: Options dictionary
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'options']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_entity" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `create_entity`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'options' in params:
            query_params.append(('options', params['options']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['fiware_token']  # noqa: E501

        return self.api_client.call_api(
            '/entities', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def list_entities(self, **kwargs):  # noqa: E501
        """list_entities  # noqa: E501

        Retrieves a list of entities that match different criteria by id, type, pattern matching (either id or type) and/or those which match a query or geographical query (see [Simple Query Language](#simple_query_language) and  [Geographical Queries](#geographical_queries)). A given entity has to match all the criteria to be retrieved (i.e., the criteria is combined in a logical AND way). Note that pattern matching query parameters are incompatible (i.e. mutually exclusive) with their corresponding exact matching parameters, i.e. `idPattern` with `id` and `typePattern` with `type`. The response payload is an array containing one object per matching entity. Each entity follows the JSON entity Representation format (described in \"JSON Entity Representation\" section).  Response code: * Successful operation uses 200 OK * Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for   more details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.list_entities(async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: A comma-separated list of elements. Retrieve entities whose ID matches one of the elements in the list. Incompatible with idPattern.
        :param str type: comma-separated list of elements. Retrieve entities whose type matches one of the elements in the list. Incompatible with `typePattern`.
        :param str id_pattern: A correctly formated regular expression. Retrieve entities whose ID matches the regular expression. Incompatible with id.
        :param str type_pattern: A correctly formated regular expression. Retrieve entities whose type matches the regular expression. Incompatible with `type`.
        :param str q: A query expression, composed of a list of statements separated by `;`, i.e., q=statement;statements;statement. See [Simple Query Language specification](#simple_query_language).
        :param str mq: A query expression for attribute metadata, composed of a list of statements separated by `;`, i.e., mq=statement1;statement2;statement3. See [Simple Query Language specification](#simple_query_language).
        :param str georel: Spatial relationship between matching entities and a reference shape. See [Geographical Queries](#geographical_queries).
        :param str geometry: Geografical area to which the query is restricted. See [Geographical Queries](#geographical_queries).
        :param str coords: List of latitude-longitude pairs of coordinates separated by `;`. See [Geographical Queries](#geographical_queries).
        :param float limit: Limits the number of entities to be retrieved
        :param float offset: Establishes the offset from where entities are retrieved
        :param str attrs: Comma-separated list of attribute names whose data are to be included in the response. The attributes are retrieved in the order specified by this parameter. If this parameter is not included, the attributes are retrieved in arbitrary order.
        :param str metadata: A list of metadata names to include in the response.
        :param str order_by: Criteria for ordering results. See \"Ordering Results\" section for details.
        :param str options: Options dictionary
        :return: list[Entity]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.list_entities_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.list_entities_with_http_info(**kwargs)  # noqa: E501
            return data

    def list_entities_with_http_info(self, **kwargs):  # noqa: E501
        """list_entities  # noqa: E501

        Retrieves a list of entities that match different criteria by id, type, pattern matching (either id or type) and/or those which match a query or geographical query (see [Simple Query Language](#simple_query_language) and  [Geographical Queries](#geographical_queries)). A given entity has to match all the criteria to be retrieved (i.e., the criteria is combined in a logical AND way). Note that pattern matching query parameters are incompatible (i.e. mutually exclusive) with their corresponding exact matching parameters, i.e. `idPattern` with `id` and `typePattern` with `type`. The response payload is an array containing one object per matching entity. Each entity follows the JSON entity Representation format (described in \"JSON Entity Representation\" section).  Response code: * Successful operation uses 200 OK * Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for   more details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.list_entities_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: A comma-separated list of elements. Retrieve entities whose ID matches one of the elements in the list. Incompatible with idPattern.
        :param str type: comma-separated list of elements. Retrieve entities whose type matches one of the elements in the list. Incompatible with `typePattern`.
        :param str id_pattern: A correctly formated regular expression. Retrieve entities whose ID matches the regular expression. Incompatible with id.
        :param str type_pattern: A correctly formated regular expression. Retrieve entities whose type matches the regular expression. Incompatible with `type`.
        :param str q: A query expression, composed of a list of statements separated by `;`, i.e., q=statement;statements;statement. See [Simple Query Language specification](#simple_query_language).
        :param str mq: A query expression for attribute metadata, composed of a list of statements separated by `;`, i.e., mq=statement1;statement2;statement3. See [Simple Query Language specification](#simple_query_language).
        :param str georel: Spatial relationship between matching entities and a reference shape. See [Geographical Queries](#geographical_queries).
        :param str geometry: Geografical area to which the query is restricted. See [Geographical Queries](#geographical_queries).
        :param str coords: List of latitude-longitude pairs of coordinates separated by `;`. See [Geographical Queries](#geographical_queries).
        :param float limit: Limits the number of entities to be retrieved
        :param float offset: Establishes the offset from where entities are retrieved
        :param str attrs: Comma-separated list of attribute names whose data are to be included in the response. The attributes are retrieved in the order specified by this parameter. If this parameter is not included, the attributes are retrieved in arbitrary order.
        :param str metadata: A list of metadata names to include in the response.
        :param str order_by: Criteria for ordering results. See \"Ordering Results\" section for details.
        :param str options: Options dictionary
        :return: list[Entity]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id', 'type', 'id_pattern', 'type_pattern', 'q', 'mq', 'georel', 'geometry', 'coords', 'limit', 'offset', 'attrs', 'metadata', 'order_by', 'options']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_entities" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'id' in params:
            query_params.append(('id', params['id']))  # noqa: E501
        if 'type' in params:
            query_params.append(('type', params['type']))  # noqa: E501
        if 'id_pattern' in params:
            query_params.append(('idPattern', params['id_pattern']))  # noqa: E501
        if 'type_pattern' in params:
            query_params.append(('typePattern', params['type_pattern']))  # noqa: E501
        if 'q' in params:
            query_params.append(('q', params['q']))  # noqa: E501
        if 'mq' in params:
            query_params.append(('mq', params['mq']))  # noqa: E501
        if 'georel' in params:
            query_params.append(('georel', params['georel']))  # noqa: E501
        if 'geometry' in params:
            query_params.append(('geometry', params['geometry']))  # noqa: E501
        if 'coords' in params:
            query_params.append(('coords', params['coords']))  # noqa: E501
        if 'limit' in params:
            query_params.append(('limit', params['limit']))  # noqa: E501
        if 'offset' in params:
            query_params.append(('offset', params['offset']))  # noqa: E501
        if 'attrs' in params:
            query_params.append(('attrs', params['attrs']))  # noqa: E501
        if 'metadata' in params:
            query_params.append(('metadata', params['metadata']))  # noqa: E501
        if 'order_by' in params:
            query_params.append(('orderBy', params['order_by']))  # noqa: E501
        if 'options' in params:
            query_params.append(('options', params['options']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['fiware_token']  # noqa: E501

        return self.api_client.call_api(
            '/entities', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Entity]',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def remove_entity(self, entity_id, **kwargs):  # noqa: E501
        """remove_entity  # noqa: E501

        Delete the entity. Response: * Successful operation uses 204 No Content * Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for   more details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remove_entity(entity_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str entity_id: Id of the entity to be deleted (required)
        :param str type: Entity type, to avoid ambiguity in the case there are several entities with the same entity id.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.remove_entity_with_http_info(entity_id, **kwargs)  # noqa: E501
        else:
            (data) = self.remove_entity_with_http_info(entity_id, **kwargs)  # noqa: E501
            return data

    def remove_entity_with_http_info(self, entity_id, **kwargs):  # noqa: E501
        """remove_entity  # noqa: E501

        Delete the entity. Response: * Successful operation uses 204 No Content * Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for   more details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.remove_entity_with_http_info(entity_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str entity_id: Id of the entity to be deleted (required)
        :param str type: Entity type, to avoid ambiguity in the case there are several entities with the same entity id.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['entity_id', 'type']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method remove_entity" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'entity_id' is set
        if ('entity_id' not in params or
                params['entity_id'] is None):
            raise ValueError("Missing the required parameter `entity_id` when calling `remove_entity`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'entity_id' in params:
            path_params['entityId'] = params['entity_id']  # noqa: E501

        query_params = []
        if 'type' in params:
            query_params.append(('type', params['type']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['fiware_token']  # noqa: E501

        return self.api_client.call_api(
            '/entities/{entityId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def replace_all_entity_attributes(self, entity_id, body, **kwargs):  # noqa: E501
        """replace_all_entity_attributes  # noqa: E501

        The request payload is an object representing the new entity attributes. The object follows the JSON entity Representation format (described in a \"JSON Entity Representation\" above), except that `id` and `type` are not allowed. The attributes previously existing in the entity are removed and replaced by the ones in the request. Response: * Successful operation uses 204 No Content * Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for   more details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.replace_all_entity_attributes(entity_id, body, async=True)
        >>> result = thread.get()

        :param async bool
        :param str entity_id: Id of the entity in question. (required)
        :param Attribute body: JSON Attribute Representation (required)
        :param str type: Entity type, to avoid ambiguity in the case there are several entities with the same entity id.
        :param str options: Operations options
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.replace_all_entity_attributes_with_http_info(entity_id, body, **kwargs)  # noqa: E501
        else:
            (data) = self.replace_all_entity_attributes_with_http_info(entity_id, body, **kwargs)  # noqa: E501
            return data

    def replace_all_entity_attributes_with_http_info(self, entity_id, body, **kwargs):  # noqa: E501
        """replace_all_entity_attributes  # noqa: E501

        The request payload is an object representing the new entity attributes. The object follows the JSON entity Representation format (described in a \"JSON Entity Representation\" above), except that `id` and `type` are not allowed. The attributes previously existing in the entity are removed and replaced by the ones in the request. Response: * Successful operation uses 204 No Content * Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for   more details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.replace_all_entity_attributes_with_http_info(entity_id, body, async=True)
        >>> result = thread.get()

        :param async bool
        :param str entity_id: Id of the entity in question. (required)
        :param Attribute body: JSON Attribute Representation (required)
        :param str type: Entity type, to avoid ambiguity in the case there are several entities with the same entity id.
        :param str options: Operations options
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['entity_id', 'body', 'type', 'options']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method replace_all_entity_attributes" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'entity_id' is set
        if ('entity_id' not in params or
                params['entity_id'] is None):
            raise ValueError("Missing the required parameter `entity_id` when calling `replace_all_entity_attributes`")  # noqa: E501
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `replace_all_entity_attributes`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'entity_id' in params:
            path_params['entityId'] = params['entity_id']  # noqa: E501

        query_params = []
        if 'type' in params:
            query_params.append(('type', params['type']))  # noqa: E501
        if 'options' in params:
            query_params.append(('options', params['options']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['fiware_token']  # noqa: E501

        return self.api_client.call_api(
            '/entities/{entityId}/attrs', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def retrieve_entity(self, entity_id, **kwargs):  # noqa: E501
        """retrieve_entity  # noqa: E501

        The response is an object representing the entity identified by the ID. The object follows the JSON entity Representation format (described in \"JSON Entity Representation\" section). This operation must return one entity element only, but there may be more than one entity with the same ID (e.g. entities with same ID but different types). In such case, an error message is returned, with the HTTP status code set to 409 Conflict. Response: * Successful operation uses 200 OK * Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for more details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.retrieve_entity(entity_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str entity_id: Id of the entity to be retrieved (required)
        :param str type: Entity type, to avoid ambiguity in case there are several entities with the same entity id.
        :param str attrs: Comma-separated list of attribute names whose data must be included in the response. The attributes are retrieved in the order specified by this parameter. If this parameter is not included, the attributes are retrieved in arbitrary order, and all the attributes of the entity are included in the response.
        :param str metadata: A list of metadata names to include in the response. See \"Filtering out attributes and metadata\" section for more detail.
        :param str options: Options dictionary
        :return: Entity
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.retrieve_entity_with_http_info(entity_id, **kwargs)  # noqa: E501
        else:
            (data) = self.retrieve_entity_with_http_info(entity_id, **kwargs)  # noqa: E501
            return data

    def retrieve_entity_with_http_info(self, entity_id, **kwargs):  # noqa: E501
        """retrieve_entity  # noqa: E501

        The response is an object representing the entity identified by the ID. The object follows the JSON entity Representation format (described in \"JSON Entity Representation\" section). This operation must return one entity element only, but there may be more than one entity with the same ID (e.g. entities with same ID but different types). In such case, an error message is returned, with the HTTP status code set to 409 Conflict. Response: * Successful operation uses 200 OK * Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for more details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.retrieve_entity_with_http_info(entity_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str entity_id: Id of the entity to be retrieved (required)
        :param str type: Entity type, to avoid ambiguity in case there are several entities with the same entity id.
        :param str attrs: Comma-separated list of attribute names whose data must be included in the response. The attributes are retrieved in the order specified by this parameter. If this parameter is not included, the attributes are retrieved in arbitrary order, and all the attributes of the entity are included in the response.
        :param str metadata: A list of metadata names to include in the response. See \"Filtering out attributes and metadata\" section for more detail.
        :param str options: Options dictionary
        :return: Entity
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['entity_id', 'type', 'attrs', 'metadata', 'options']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method retrieve_entity" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'entity_id' is set
        if ('entity_id' not in params or
                params['entity_id'] is None):
            raise ValueError("Missing the required parameter `entity_id` when calling `retrieve_entity`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'entity_id' in params:
            path_params['entityId'] = params['entity_id']  # noqa: E501

        query_params = []
        if 'type' in params:
            query_params.append(('type', params['type']))  # noqa: E501
        if 'attrs' in params:
            query_params.append(('attrs', params['attrs']))  # noqa: E501
        if 'metadata' in params:
            query_params.append(('metadata', params['metadata']))  # noqa: E501
        if 'options' in params:
            query_params.append(('options', params['options']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['fiware_token']  # noqa: E501

        return self.api_client.call_api(
            '/entities/{entityId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Entity',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def retrieve_entity_attributes(self, entity_id, **kwargs):  # noqa: E501
        """retrieve_entity_attributes  # noqa: E501

        This request is similar to retreiving the whole entity, however this one omits the `id` and `type` fields. Just like the general request of getting an entire entity, this operation must return only one entity element. If more than one entity with the same ID is found (e.g. entities with same ID but different type), an error message is returned, with the HTTP status code set to 409 Conflict. Response: * Successful operation uses 200 OK * Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for   more details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.retrieve_entity_attributes(entity_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str entity_id: Id of the entity to be retrieved (required)
        :param str type: Entity type, to avoid ambiguity in the case there are several entities with the same entity id.
        :param str attrs: Comma-separated list of attribute names whose data are to be included in the response. The attributes are retrieved in the order specified by this parameter. If this parameter is not included, the attributes are retrieved in arbitrary order, and all the attributes of the entity are included in the response.
        :param str metadata: A list of metadata names to include in the response. See \"Filtering out attributes and metadata\" section for more detail.
        :param str options: Options dictionary
        :return: Attribute
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.retrieve_entity_attributes_with_http_info(entity_id, **kwargs)  # noqa: E501
        else:
            (data) = self.retrieve_entity_attributes_with_http_info(entity_id, **kwargs)  # noqa: E501
            return data

    def retrieve_entity_attributes_with_http_info(self, entity_id, **kwargs):  # noqa: E501
        """retrieve_entity_attributes  # noqa: E501

        This request is similar to retreiving the whole entity, however this one omits the `id` and `type` fields. Just like the general request of getting an entire entity, this operation must return only one entity element. If more than one entity with the same ID is found (e.g. entities with same ID but different type), an error message is returned, with the HTTP status code set to 409 Conflict. Response: * Successful operation uses 200 OK * Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for   more details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.retrieve_entity_attributes_with_http_info(entity_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str entity_id: Id of the entity to be retrieved (required)
        :param str type: Entity type, to avoid ambiguity in the case there are several entities with the same entity id.
        :param str attrs: Comma-separated list of attribute names whose data are to be included in the response. The attributes are retrieved in the order specified by this parameter. If this parameter is not included, the attributes are retrieved in arbitrary order, and all the attributes of the entity are included in the response.
        :param str metadata: A list of metadata names to include in the response. See \"Filtering out attributes and metadata\" section for more detail.
        :param str options: Options dictionary
        :return: Attribute
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['entity_id', 'type', 'attrs', 'metadata', 'options']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method retrieve_entity_attributes" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'entity_id' is set
        if ('entity_id' not in params or
                params['entity_id'] is None):
            raise ValueError("Missing the required parameter `entity_id` when calling `retrieve_entity_attributes`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'entity_id' in params:
            path_params['entityId'] = params['entity_id']  # noqa: E501

        query_params = []
        if 'type' in params:
            query_params.append(('type', params['type']))  # noqa: E501
        if 'attrs' in params:
            query_params.append(('attrs', params['attrs']))  # noqa: E501
        if 'metadata' in params:
            query_params.append(('metadata', params['metadata']))  # noqa: E501
        if 'options' in params:
            query_params.append(('options', params['options']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['fiware_token']  # noqa: E501

        return self.api_client.call_api(
            '/entities/{entityId}/attrs', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Attribute',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_existing_entity_attributes(self, entity_id, body, **kwargs):  # noqa: E501
        """update_existing_entity_attributes  # noqa: E501

        The request payload is an object representing the attributes to update. The object follows the JSON entity Representation format (described in \"JSON Entity Representation\" section), except that `id` and `type` are not allowed. The entity attributes are updated with the ones in the payload. In addition to that, if one or more attributes in the payload doesn't exist in the entity, an error is returned. Response: * Successful operation uses 204 No Content * Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for   more details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.update_existing_entity_attributes(entity_id, body, async=True)
        >>> result = thread.get()

        :param async bool
        :param str entity_id: Id of the entity to be updated (required)
        :param Attribute body: JSON Attribute Representation (required)
        :param str type: Entity type, to avoid ambiguity in case there are several entities with the same entity id.
        :param str options: Operations options
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.update_existing_entity_attributes_with_http_info(entity_id, body, **kwargs)  # noqa: E501
        else:
            (data) = self.update_existing_entity_attributes_with_http_info(entity_id, body, **kwargs)  # noqa: E501
            return data

    def update_existing_entity_attributes_with_http_info(self, entity_id, body, **kwargs):  # noqa: E501
        """update_existing_entity_attributes  # noqa: E501

        The request payload is an object representing the attributes to update. The object follows the JSON entity Representation format (described in \"JSON Entity Representation\" section), except that `id` and `type` are not allowed. The entity attributes are updated with the ones in the payload. In addition to that, if one or more attributes in the payload doesn't exist in the entity, an error is returned. Response: * Successful operation uses 204 No Content * Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for   more details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.update_existing_entity_attributes_with_http_info(entity_id, body, async=True)
        >>> result = thread.get()

        :param async bool
        :param str entity_id: Id of the entity to be updated (required)
        :param Attribute body: JSON Attribute Representation (required)
        :param str type: Entity type, to avoid ambiguity in case there are several entities with the same entity id.
        :param str options: Operations options
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['entity_id', 'body', 'type', 'options']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_existing_entity_attributes" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'entity_id' is set
        if ('entity_id' not in params or
                params['entity_id'] is None):
            raise ValueError("Missing the required parameter `entity_id` when calling `update_existing_entity_attributes`")  # noqa: E501
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `update_existing_entity_attributes`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'entity_id' in params:
            path_params['entityId'] = params['entity_id']  # noqa: E501

        query_params = []
        if 'type' in params:
            query_params.append(('type', params['type']))  # noqa: E501
        if 'options' in params:
            query_params.append(('options', params['options']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['fiware_token']  # noqa: E501

        return self.api_client.call_api(
            '/entities/{entityId}/attrs', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_or_append_entity_attributes(self, entity_id, body, **kwargs):  # noqa: E501
        """update_or_append_entity_attributes  # noqa: E501

        The request payload is an object representing the attributes to append or update. The object follows the JSON entity Representation format (described in \"JSON Entity Representation\" section), except that `id` and `type` are not allowed. The entity attributes are updated with the ones in the payload, depending on whether the `append` operation option is used or not. * If `append` is not used: the entity attributes are updated (if they previously exist) or appended   (if they don't previously exist) with the ones in the payload. * If `append` is used (i.e. strict append semantics): all the attributes in the payload not   previously existing in the entity are appended. In addition to that, in case some of the   attributes in the payload already exist in the entity, an error is returned.    Response: * Successful operation uses 204 No Content * Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for   more details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.update_or_append_entity_attributes(entity_id, body, async=True)
        >>> result = thread.get()

        :param async bool
        :param str entity_id: Entity id to be updated (required)
        :param Attribute body: JSON Attribute Representation (required)
        :param str type: Entity type, to avoid ambiguity in case there are several entities with the same entity id.
        :param str options: Operations options
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.update_or_append_entity_attributes_with_http_info(entity_id, body, **kwargs)  # noqa: E501
        else:
            (data) = self.update_or_append_entity_attributes_with_http_info(entity_id, body, **kwargs)  # noqa: E501
            return data

    def update_or_append_entity_attributes_with_http_info(self, entity_id, body, **kwargs):  # noqa: E501
        """update_or_append_entity_attributes  # noqa: E501

        The request payload is an object representing the attributes to append or update. The object follows the JSON entity Representation format (described in \"JSON Entity Representation\" section), except that `id` and `type` are not allowed. The entity attributes are updated with the ones in the payload, depending on whether the `append` operation option is used or not. * If `append` is not used: the entity attributes are updated (if they previously exist) or appended   (if they don't previously exist) with the ones in the payload. * If `append` is used (i.e. strict append semantics): all the attributes in the payload not   previously existing in the entity are appended. In addition to that, in case some of the   attributes in the payload already exist in the entity, an error is returned.    Response: * Successful operation uses 204 No Content * Errors use a non-2xx and (optionally) an error payload. See subsection on \"Error Responses\" for   more details.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.update_or_append_entity_attributes_with_http_info(entity_id, body, async=True)
        >>> result = thread.get()

        :param async bool
        :param str entity_id: Entity id to be updated (required)
        :param Attribute body: JSON Attribute Representation (required)
        :param str type: Entity type, to avoid ambiguity in case there are several entities with the same entity id.
        :param str options: Operations options
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['entity_id', 'body', 'type', 'options']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_or_append_entity_attributes" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'entity_id' is set
        if ('entity_id' not in params or
                params['entity_id'] is None):
            raise ValueError("Missing the required parameter `entity_id` when calling `update_or_append_entity_attributes`")  # noqa: E501
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `update_or_append_entity_attributes`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'entity_id' in params:
            path_params['entityId'] = params['entity_id']  # noqa: E501

        query_params = []
        if 'type' in params:
            query_params.append(('type', params['type']))  # noqa: E501
        if 'options' in params:
            query_params.append(('options', params['options']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['fiware_token']  # noqa: E501

        return self.api_client.call_api(
            '/entities/{entityId}/attrs', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
